package com.cfwx.rox.businesssync.market.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "EjdbWebServiceSoap", targetNamespace = "http://www.icfwx.com.cn/")
public interface EjdbWebServiceSoap {

	/**
	 * 
	 * @param procedure
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetData", action = "http://www.icfwx.com.cn/GetData")
	@WebResult(name = "GetDataResult", targetNamespace = "http://www.icfwx.com.cn/")
	@RequestWrapper(localName = "GetData", targetNamespace = "http://www.icfwx.com.cn/", className = "org.tempuri.GetData")
	@ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://www.icfwx.com.cn/", className = "org.tempuri.GetDataResponse")
	public String getData(
			@WebParam(name = "procedure", targetNamespace = "http://www.icfwx.com.cn/") String procedure);

}
