//文件创建时间:2012年05月19日 14时20分31秒
//数据修改时间:
#if !defined(_FXDEF_DEFINE_H)
#define _FIDDEF_DEFINE_H
#define FID_BCZJYE               501 //C
#define FID_BFXJJ                502 //C
#define FID_BGHF                 503 //C
#define FID_BJE                  504 //C
#define FID_BJSF                 505 //C
#define FID_BPGDH                506 //C
#define FID_CODE                 507 //C
#define FID_MESSAGE              508 //C
#define FID_BSL                  509 //C
#define FID_BYHS                 510 //C
#define FID_BZ                   511 //C
#define FID_BZBM                 512 //C
#define FID_BZGF                 513 //C
#define FID_BZMC                 514 //C
#define FID_CBBD                 515 //C
#define FID_MENUID_HC            516 //C
#define FID_HLJE                 517 //C
#define FID_CDMC                 518 //C
#define FID_CDTIME               519 //C
#define FID_CDTS                 520 //C
#define FID_CDWZID               521 //C
#define FID_CJBH                 522 //C
#define FID_CJGY                 523 //C
#define FID_CJJE                 524 //C
#define FID_CJJG                 525 //C
#define FID_CJRQ                 526 //C
#define FID_CJSJ                 527 //C
#define FID_CJSL                 528 //C
#define FID_CKLL                 529 //C
#define FID_YKBD                 530 //C
#define FID_CSZ                  531 //C
#define FID_DH                   532 //C
#define FID_DJLB                 533 //C
#define FID_DH_SQCZR             534 //C
#define FID_DZ_SQCZR             535 //C
#define FID_MM_SQCZR             536 //C
#define FID_QX_SQCZR             537 //C
#define FID_XWID                 538 //C
#define FID_XM_SQCZR             539 //C
#define FID_DRMCCJJE             540 //C
#define FID_DRMCCJSL             541 //C
#define FID_DRMCJDZJ             542 //C
#define FID_DRMCWTSL             543 //C
#define FID_DRMRCJJE             544 //C
#define FID_DRMRCJSL             545 //C
#define FID_DRMRDJZJ             546 //C
#define FID_DRMRWTSL             547 //C
#define FID_DRQS                 548 //C
#define FID_DTB                  549 //C
#define FID_DZ                   550 //C
#define FID_DZLX                 551 //C
#define FID_EMAIL                552 //C
#define FID_EN_BZ                553 //C
#define FID_EN_JYS               554 //C
#define FID_EN_KHH               555 //C
#define FID_EN_KHQZ              556 //C
#define FID_EN_YYB               557 //C
#define FID_EN_ZQLB              558 //C
#define FID_EX_KHH               559 //C
#define FID_EX_KHQZ              560 //C
#define FID_EX_YYB               561 //C
#define FID_EX_ZQLB              562 //C
#define FID_FATHERID             563 //C
#define FID_AUTOSAVE             564 //C
#define FID_FKEY                 565 //C
#define FID_FLDM                 566 //C
#define FID_FLMC                 567 //C
#define FID_FLTSL                568 //C
#define FID_FSYYB                569 //C
#define FID_FWXM                 570 //C
#define FID_GDH                  571 //C
#define FID_GDLB                 572 //C
#define FID_ZJBH_GDH             573 //C
#define FID_GDZDSX               574 //C
#define FID_GDXM                 575 //C
#define FID_GJDM                 576 //C
#define FID_GMRQ                 577 //C
#define FID_DATE                 578 //C
#define FID_HKEY                 579 //C
#define FID_HKEYMASK             580 //C
#define FID_SHZD                 581 //C
#define FID_IBM                  582 //C
#define FID_JJR                  583 //C
#define FID_JJRLB                584 //C
#define FID_JJRMM                585 //C
#define FID_JJRQX                586 //C
#define FID_JKP                  587 //C
#define FID_JSDM                 588 //C
#define FID_JSMC                 589 //C
#define FID_JSRQ                 590 //C
#define FID_JYDW                 591 //C
#define FID_JYFL                 592 //C
#define FID_JYFW                 593 //C
#define FID_JYJW                 594 //C
#define FID_JYLB                 595 //C
#define FID_JYLBMC               596 //C
#define FID_JYLBXZ               597 //C
#define FID_JYMM                 598 //C
#define FID_JYS                  599 //C
#define FID_JYSXH                600 //C
#define FID_JYSJC                601 //C
#define FID_JYSQC                602 //C
#define FID_KCRQ                 603 //C
#define FID_KEYMASK              604 //C
#define FID_KHH                  605 //C
#define FID_KHJB                 606 //C
#define FID_KHJL                 607 //C
#define FID_KHLB                 608 //C
#define FID_KHQC                 609 //C
#define FID_KHQZ                 610 //C
#define FID_KHRQ                 611 //C
#define FID_KHSX                 612 //C
#define FID_KHXM                 613 //C
#define FID_LSH_ZR               614 //C
#define FID_KMCSL                615 //C
#define FID_KMRSL                616 //C
#define FID_KQZJ                 617 //C
#define FID_KSRQ                 618 //C
#define FID_KYZJ                 619 //C
#define FID_LL                   620 //C
#define FID_YJLX                 621 //C
#define FID_LXJS                 622 //C
#define FID_LXS                  623 //C
#define FID_LXSL                 624 //C
#define FID_MCJE                 625 //C
#define FID_MCJJ                 626 //C
#define FID_MCJS                 627 //C
#define FID_MCSL                 628 //C
#define FID_MENUID               629 //C
#define FID_MKBH                 630 //C
#define FID_MM                   631 //C
#define FID_MMXZ                 632 //C
#define FID_YKTZMS               633 //C
#define FID_MRJE                 634 //C
#define FID_JYMQZ                635 //C
#define FID_MRJJ                 636 //C
#define FID_MRJS                 637 //C
#define FID_MRSL                 638 //C
#define FID_NBMC                 639 //C
#define FID_NEWMM                640 //C
#define FID_NODE                 641 //C
#define FID_NOTE                 642 //C
#define FID_PYDM                 643 //C
#define FID_PZBZ                 644 //C
#define FID_ZJZH_ZR              645 //C
#define FID_QSJE                 646 //C
#define FID_QSZJ                 647 //C
#define FID_QYBM                 648 //C
#define FID_QZFW                 649 //C
#define FID_QZMC                 650 //C
#define FID_RQ                   651 //C
#define FID_RZJE                 652 //C
#define FID_RZLL                 653 //C
#define FID_SFXJJ                654 //C
#define FID_SGHF                 655 //C
#define FID_SJCD                 656 //C
#define FID_SJE                  657 //C
#define FID_SJJJR                658 //C
#define FID_SJSF                 659 //C
#define FID_SJYYB                660 //C
#define FID_SLXZ                 661 //C
#define FID_CZCS                 662 //C
#define FID_SRZJYE               663 //C
#define FID_SSL                  664 //C
#define FID_SXLB                 665 //C
#define FID_SYHS                 666 //C
#define FID_SZGF                 667 //C
#define FID_T0JS                 668 //C
#define FID_T1JS                 669 //C
#define FID_T2JS                 670 //C
#define FID_TBCBJ                671 //C
#define FID_TBTS                 672 //C
#define FID_TJFL                 673 //C
#define FID_TZJS                 674 //C
#define FID_TZLL                 675 //C
#define FID_CBTZMS               676 //C
#define FID_USERID               677 //C
#define FID_USERNAME             678 //C
#define FID_VALUE                679 //C
#define FID_WTFS                 680 //C
#define FID_WTH                  681 //C
#define FID_WTJG                 682 //C
#define FID_WTLB                 683 //C
#define FID_WTSL                 684 //C
#define FID_JSDM_HC              685 //C
#define FID_WTSX                 686 //C
#define FID_WTXX                 687 //C
#define FID_XHRQ                 688 //C
#define FID_XLDM                 689 //C
#define FID_XM                   690 //C
#define FID_GDZT                 691 //C
#define FID_YHDM                 692 //C
#define FID_YHZH                 693 //C
#define FID_YWKM                 694 //C
#define FID_YWLB                 695 //C
#define FID_YWMC                 696 //C
#define FID_YYB                  697 //C
#define FID_KHH_ZR               698 //C
#define FID_CLSJ                 699 //C
#define FID_KHXM_ZR              700 //C
#define FID_GYDM_ZP              701 //C
#define FID_YZBM                 702 //C
#define FID_ZDBJ                 703 //C
#define FID_ZDJ                  704 //C
#define FID_EN_WTH               705 //C
#define FID_ZGBJ                 706 //C
#define FID_ZGJ                  707 //C
#define FID_KHFLFS               708 //C
#define FID_ZHYE                 709 //C
#define FID_ZHZT                 710 //C
#define FID_ZJBH                 711 //C
#define FID_YJDJCL               712 //C
#define FID_ZJLB                 713 //C
#define FID_ZJMM                 714 //C
#define FID_ZJYE                 715 //C
#define FID_ZJZH                 716 //C
#define FID_GDH_OLD              717 //C
#define FID_LJS1                 718 //C
#define FID_ZQDM                 719 //C
#define FID_ZQLB                 720 //C
#define FID_ZQLBMC               721 //C
#define FID_ZQMC                 722 //C
#define FID_ZQQC                 723 //C
#define FID_ZQSL                 724 //C
#define FID_ZSBH                 725 //C
#define FID_ZSP                  726 //C
#define FID_ZZHBZ                727 //C
#define FID_ZTB                  728 //C
#define FID_ZXJ                  729 //C
#define FID_ZY                   730 //C
#define FID_ZYDM                 731 //C
#define FID_ZZFS                 732 //C
#define FID_ZZJE                 733 //C
#define FID_ZZKZ                 734 //C
#define FID_MMLB                 735 //C
#define FID_HTHQZ                736 //C
#define FID_NEWQZ                737 //C
#define FID_EN_ZJZH              738 //C
#define FID_LOGICAL              739 //C
#define FID_KHFW                 740 //C
#define FID_SQFS                 741 //C
#define FID_CKCS                 742 //C
#define FID_CKZE                 743 //C
#define FID_CKDBSX               744 //C
#define FID_QKCS                 745 //C
#define FID_QKZE                 746 //C
#define FID_QKDBSX               747 //C
#define FID_TBBBJ                748 //C
#define FID_TBFDYK               749 //C
#define FID_WTSJ                 750 //C
#define FID_SBSJ                 751 //C
#define FID_MMLBSM               752 //C
#define FID_SBJG                 753 //C
#define FID_SBJGSM               754 //C
#define FID_CXBZ                 755 //C
#define FID_DLSF                 756 //C
#define FID_JCCL                 757 //C
#define FID_WJSSL                758 //C
#define FID_CDCZDX               759 //C
#define FID_ZXSZ                 760 //C
#define FID_FDYK                 761 //C
#define FID_DGDHBZ               762 //C
#define FID_BROWINDEX            763 //C
#define FID_DJZJ                 764 //C
#define FID_LOGINPWD             765 //C
#define FID_S1                   766 //C
#define FID_S2                   767 //C
#define FID_S3                   768 //C
#define FID_S4                   769 //C
#define FID_S5                   770 //C
#define FID_S6                   771 //C
#define FID_YSJE                 772 //C
#define FID_LXSR                 773 //C
#define FID_LXFC                 774 //C
#define FID_BZS1                 775 //C
#define FID_BCZQSL               776 //C
#define FID_BRZQSL               777 //C
#define FID_BRZJYE               778 //C
#define FID_GDJG                 779 //C
#define FID_CSID                 780 //C
#define FID_JMLX                 781 //C
#define FID_SQLB                 782 //C
#define FID_DLXH                 783 //C
#define FID_ZPJE                 784 //C
#define FID_GPSZ                 785 //C
#define FID_MMYZFS               786 //C
#define FID_FZYZFS               787 //C
#define FID_COUNT                788 //C
#define FID_GDHH                 789 //C
#define FID_GDHL                 790 //C
#define FID_ZQDML                791 //C
#define FID_ENDWTH               792 //C
#define FID_LOGINID              793 //C
#define FID_ZHXM                 794 //C
#define FID_JSZH                 795 //C
#define FID_FAX                  796 //C
#define FID_LSH                  797 //C
#define FID_HOST                 798 //C
#define FID_TZLX                 799 //C
#define FID_GSFL                 800 //C
#define FID_SRFS                 801 //C
#define FID_XJZC                 802 //C
#define FID_SRYE                 803 //C
#define FID_ZHSX                 804 //C
#define FID_WJSJE                805 //C
#define FID_CQBZ                 806 //C
#define FID_YZZZBZ               807 //C
#define FID_FSJE                 808 //C
#define FID_NEWKHJL              809 //C
#define FID_SCZJYE               810 //C
#define FID_SQPCH                811 //C
#define FID_DJRQ                 812 //C
#define FID_EN_GSFL              813 //C
#define FID_ITEM                 814 //C
#define FID_XGRQ                 815 //C
#define FID_CSJB                 816 //C
#define FID_SXMC                 817 //C
#define FID_PZH2                 818 //C
#define FID_LPID                 819 //C
#define FID_LPBM                 820 //C
#define FID_LPMC                 821 //C
#define FID_LPJZ                 822 //C
#define FID_ZSFS                 823 //C
#define FID_ZCKZED               824 //C
#define FID_ZJKZED               825 //C
#define FID_DJJE                 826 //C
#define FID_YCDJJE               827 //C
#define FID_QSDM                 828 //C
#define FID_QSMC                 829 //C
#define FID_JGSM                 830 //C
#define FID_CLRQ                 831 //C
#define FID_JGBM                 832 //C
#define FID_JGMC                 833 //C
#define FID_JGJC                 834 //C
#define FID_CITY                 835 //C
#define FID_PROVINCE             836 //C
#define FID_SJJG                 837 //C
#define FID_SJJGLB               838 //C
#define FID_JGLB                 839 //C
#define FID_EN_SJJGLB            840 //C
#define FID_EN_JYLB              841 //C
#define FID_MRJG1                842 //C
#define FID_MRSL1                843 //C
#define FID_MRJG2                844 //C
#define FID_MRSL2                845 //C
#define FID_MRJG3                846 //C
#define FID_MRSL3                847 //C
#define FID_MRJG4                848 //C
#define FID_MRSL4                849 //C
#define FID_MCJG1                850 //C
#define FID_MCSL1                851 //C
#define FID_MCJG2                852 //C
#define FID_MCSL2                853 //C
#define FID_MCJG3                854 //C
#define FID_MCSL3                855 //C
#define FID_MCJG4                856 //C
#define FID_MCSL4                857 //C
#define FID_DYBL                 858 //C
#define FID_JJRXM                859 //C
#define FID_TPBZ                 860 //C
#define FID_JSLX                 861 //C
#define FID_HBXH                 862 //C
#define FID_SBGDH                863 //C
#define FID_WTGY                 864 //C
#define FID_FSSJ                 865 //C
#define FID_WTZKXS               866 //C
#define FID_CXZKXS               867 //C
#define FID_QTZKXS               868 //C
#define FID_ZQSZ                 869 //C
#define FID_KYZJXE               870 //C
#define FID_XMLSH                871 //C
#define FID_ZCZH                 872 //C
#define FID_ZCBL                 873 //C
#define FID_SFFS                 874 //C
#define FID_SFBZ                 875 //C
#define FID_JFFS                 876 //C
#define FID_JFQD                 877 //C
#define FID_JFDW                 878 //C
#define FID_CZSJ                 879 //C
#define FID_CLJG                 880 //C
#define FID_GYFL                 881 //C
#define FID_WBGYDM               882 //C
#define FID_XQXZ                 883 //C
#define FID_ZCXZ                 884 //C
#define FID_SLSX                 885 //C
#define FID_CDSL                 886 //C
#define FID_YJZKBL               887 //C
#define FID_FJFZKBL              888 //C
#define FID_BH                   889 //C
#define FID_SHXYM                890 //C
#define FID_ZLLB                 891 //C
#define FID_CDJSP                892 //C
#define FID_EN_NODE              893 //C
#define FID_EN_MYYYB             894 //C
#define FID_ZJGMRQ               895 //C
#define FID_JGSX                 896 //C
#define FID_CDSX                 897 //C
#define FID_BM                   898 //C
#define FID_BMSM                 899 //C
#define FID_CDDLL                900 //C
#define FID_SXZ                  901 //C
#define FID_YHSX                 902 //C
#define FID_YHYW                 903 //C
#define FID_ZQYW                 904 //C
#define FID_ZJMMXY               905 //C
#define FID_JYMMXY               906 //C
#define FID_YHMMXY               907 //C
#define FID_YHMC                 908 //C
#define FID_HBLB                 909 //C
#define FID_WBZHMM               910 //C
#define FID_DYBS                 911 //C
#define FID_SQH                  912 //C
#define FID_WBLSH                913 //C
#define FID_BDDJJE               914 //C
#define FID_CJBS                 915 //C
#define FID_SHLB                 916 //C
#define FID_SHJG                 917 //C
#define FID_YEGXSJ               918 //C
#define FID_QSMM                 919 //C
#define FID_MMMY                 920 //C
#define FID_CSMY                 921 //C
#define FID_FJXX                 922 //C
#define FID_WBCLJG               923 //C
#define FID_SQWD                 924 //C
#define FID_XYBZ                 925 //C
#define FID_CXSQH                926 //C
#define FID_JYBS                 927 //C
#define FID_CLLB                 928 //C
#define FID_ZHLB                 929 //C
#define FID_FQF                  930 //C
#define FID_HZBS                 931 //C
#define FID_HZJE                 932 //C
#define FID_LY                   933 //C
#define FID_WDH                  934 //C
#define FID_QD1                  935 //C
#define FID_QD2                  936 //C
#define FID_QD3                  937 //C
#define FID_QD4                  938 //C
#define FID_QD5                  939 //C
#define FID_BL1                  940 //C
#define FID_BL2                  941 //C
#define FID_BL3                  942 //C
#define FID_BL4                  943 //C
#define FID_BL5                  944 //C
#define FID_KHJCGX               945 //C
#define FID_SYZH1                946 //C
#define FID_SYZH2                947 //C
#define FID_JSTS                 948 //C
#define FID_TJJYR                949 //C
#define FID_TJTS                 950 //C
#define FID_FPBL                 951 //C
#define FID_ZKFS                 952 //C
#define FID_ZJED                 953 //C
#define FID_ZCED                 954 //C
#define FID_GLF                  955 //C
#define FID_YJDX                 956 //C
#define FID_EX_JYLB              957 //C
#define FID_BDSL                 958 //C
#define FID_HZFS                 959 //C
#define FID_LPSL                 960 //C
#define FID_LXBJ                 961 //C
#define FID_KLX                  962 //C
#define FID_KMC                  963 //C
#define FID_BSC                  964 //C
#define FID_BSCKSWZ              965 //C
#define FID_FJC                  966 //C
#define FID_FJCKSWZ              967 //C
#define FID_KHKSWZ               968 //C
#define FID_KHCD                 969 //C
#define FID_EN_YWKM              970 //C
#define FID_ZRSZ                 971 //C
#define FID_NEXTDATA             972 //C
#define FID_SYL                  973 //C
#define FID_FHS1                 974 //C
#define FID_GJBM1                975 //C
#define FID_GJBM2                976 //C
#define FID_GJBM3                977 //C
#define FID_GJMC                 978 //C
#define FID_EGJMC                979 //C
#define FID_CCCB                 980 //C
#define FID_BDRQ                 981 //C
#define FID_MMXYLX               982 //C
#define FID_XZSJ                 983 //C
#define FID_KHDXLX               984 //C
#define FID_JYSXGX               985 //C
#define FID_BZXGX                986 //C
#define FID_QZXGX                987 //C
#define FID_EXFLG                988 //C
#define FID_MAX_D                989 //C
#define FID_MIN_D                990 //C
#define FID_MAX_L                991 //C
#define FID_MIN_L                992 //C
#define FID_GYFJQX               993 //C
#define FID_ZHTZE                994 //C
#define FID_QSJE_B               995 //C
#define FID_QSJE_S               996 //C
#define FID_FDYK_TB              997 //C
#define FID_LLCSLB               998 //C
#define FID_EX_JJR               999 //C
#define FID_FHFS                1000 //C
#define FID_BZ_FH               1001 //C
#define FID_HBDHBL              1002 //C
#define FID_SYZH3               1003 //C
#define FID_SYBL1               1004 //C
#define FID_SYBL2               1005 //C
#define FID_SYBL3               1006 //C
#define FID_GDKZSX              1007 //C
#define FID_RCKHH               1008 //C
#define FID_RQ2                 1009 //C
#define FID_EN_YXZZDM           1010 //C
#define FID_SBWTH               1011 //C
#define FID_CITYID              1012 //C
#define FID_DDLX                1013 //C
#define FID_SECTIONID           1014 //C
#define FID_SECTION             1015 //C
#define FID_SFZQ                1016 //C
#define FID_WTPCH               1017 //C
#define FID_KXDLSF              1018 //C
#define FID_EN_YWLB             1019 //C
#define FID_BZDM                1020 //C
#define FID_WBDM                1021 //C
#define FID_CSDM                1022 //C
#define FID_CSMC                1023 //C
#define FID_QZSM                1024 //C
#define FID_EN_FJBZ             1025 //C
#define FID_HYMC                1026 //C
#define FID_JSJG                1027 //C
#define FID_CWLX                1028 //C
#define FID_CWDM                1029 //C
#define FID_CWSM                1030 //C
#define FID_ZXZS                1031 //C
#define FID_TZEBZ               1032 //C
#define FID_KBBZ                1033 //C
#define FID_KHTZFL              1034 //C
#define FID_ZJZR                1035 //C
#define FID_ZJZC                1036 //C
#define FID_SZZR                1037 //C
#define FID_SZZC                1038 //C
#define FID_MKKZ                1039 //C
#define FID_MFCS                1040 //C
#define FID_XZCS                1041 //C
#define FID_SJSX_A              1042 //C
#define FID_SJSX_S              1043 //C
#define FID_MMCSCS              1044 //C
#define FID_ZDJDTS              1045 //C
#define FID_MFHQCS              1046 //C
#define FID_HQSFSX              1047 //C
#define FID_HKSFSX              1048 //C
#define FID_SJSFSX              1049 //C
#define FID_ZSFSX               1050 //C
#define FID_DBYJXX              1051 //C
#define FID_DBYJSX              1052 //C
#define FID_ZCJJE               1053 //C
#define FID_YJDJFS              1054 //C
#define FID_FHGY                1055 //C
#define FID_TJZQLB              1056 //C
#define FID_DJJSFS              1057 //C
#define FID_FDBH                1058 //C
#define FID_CFCDBZ              1059 //C
#define FID_ZHDM                1060 //C
#define FID_TZDW                1061 //C
#define FID_TZXX                1062 //C
#define FID_SYZKXS              1063 //C
#define FID_SYTZFS              1064 //C
#define FID_TZJESX              1065 //C
#define FID_ZJLCDS              1066 //C
#define FID_TZBDJE              1067 //C
#define FID_ZHKHH               1068 //C
#define FID_ZHZJZH              1069 //C
#define FID_LCJZJE              1070 //C
#define FID_LCFHJE              1071 //C
#define FID_SYZTZBZ             1072 //C
#define FID_SYZTZZQ             1073 //C
#define FID_LCZSY               1074 //C
#define FID_SYZCJE              1075 //C
#define FID_SYZTZE              1076 //C
#define FID_XYBH                1077 //C
#define FID_LCTZJE              1078 //C
#define FID_SGDM                1079 //C
#define FID_CLBZ                1080 //C
#define FID_FPSY                1081 //C
#define FID_GBZQL               1082 //C
#define FID_SGSL                1083 //C
#define FID_SGJG                1084 //C
#define FID_SSRQ                1085 //C
#define FID_HKRQ                1086 //C
#define FID_SSDM                1087 //C
#define FID_PHDM                1088 //C
#define FID_HKDM                1089 //C
#define FID_SGRQ                1090 //C
#define FID_JEBL                1091 //C
#define FID_LCJZQTJE            1092 //C
#define FID_HZGDH               1093 //C
#define FID_SYDX                1094 //C
#define FID_JYLJSFS             1095 //C
#define FID_JYLLJZQ             1096 //C
#define FID_DJFS                1097 //C
#define FID_BBJ                 1098 //C
#define FID_HZLB                1099 //C
#define FID_FSJE_LCBJ           1100 //C
#define FID_BCYE_LCBJ           1101 //C
#define FID_FSJE_SY             1102 //C
#define FID_BCYE_SY             1103 //C
#define FID_FSJE_BZJ            1104 //C
#define FID_BCYE_BZJ            1105 //C
#define FID_HZLBMC              1106 //C
#define FID_KSFW                1107 //C
#define FID_JSFW                1108 //C
#define FID_ZDKZBZ              1109 //C
#define FID_KHS                 1110 //C
#define FID_XHS                 1111 //C
#define FID_ZHS                 1112 //C
#define FID_ZDGDHS              1113 //C
#define FID_CXZDHS              1114 //C
#define FID_CCGDHS              1115 //C
#define FID_TJZJYE              1116 //C
#define FID_TJZJCK              1117 //C
#define FID_TJZJQK              1118 //C
#define FID_TJZJGP              1119 //C
#define FID_TJJSGP              1120 //C
#define FID_TJGPSZ              1121 //C
#define FID_TJZZC               1122 //C
#define FID_FDB1                1123 //C
#define FID_FDE1                1124 //C
#define FID_FDB2                1125 //C
#define FID_FDE2                1126 //C
#define FID_FDB3                1127 //C
#define FID_FDE3                1128 //C
#define FID_FDB4                1129 //C
#define FID_FDE4                1130 //C
#define FID_FDB5                1131 //C
#define FID_FDE5                1132 //C
#define FID_FDB6                1133 //C
#define FID_FDE6                1134 //C
#define FID_TJJGGS              1135 //C
#define FID_TJJGSJ              1136 //C
#define FID_QSBZ                1137 //C
#define FID_TZJE                1138 //C
#define FID_WJSZJ               1139 //C
#define FID_ZJDJLSH             1140 //C
#define FID_YDZD                1141 //C
#define FID_YDZDSM              1142 //C
#define FID_YDSJ                1143 //C
#define FID_JCJJE               1144 //C
#define FID_YXHS                1145 //C
#define FID_CJSLBL              1146 //C
#define FID_CJJEBL              1147 //C
#define FID_S1BL                1148 //C
#define FID_ZZCBL1              1149 //C
#define FID_ZZCBL2              1150 //C
#define FID_ZSLBL1              1151 //C
#define FID_ZSLBL2              1152 //C
#define FID_ZHSBL1              1153 //C
#define FID_ZHSBL2              1154 //C
#define FID_JEXX                1155 //C
#define FID_ZQDJLSH             1156 //C
#define FID_WTSB                1157 //C
#define FID_QDBZ                1158 //C
#define FID_WBZH                1159 //C
#define FID_SQBH                1160 //C
#define FID_WBCKKY              1161 //C
#define FID_WBCKKQ              1162 //C
#define FID_WBDJJE              1163 //C
#define FID_JYXZ                1164 //C
#define FID_ZJXYFS              1165 //C
#define FID_HBBZ                1166 //C
#define FID_ZJHZFS              1167 //C
#define FID_DRQKJE              1168 //C
#define FID_JGKZBZ              1169 //C
#define FID_ZZJSSJ              1170 //C
#define FID_CZDRZXBZ            1171 //C
#define FID_LSH_LXS             1172 //C
#define FID_LX                  1173 //C
#define FID_ZJMXLSH             1174 //C
#define FID_YSSL                1175 //C
#define FID_BBYK                1176 //C
#define FID_JYSFY               1177 //C
#define FID_BCJKYE              1178 //C
#define FID_KSGSL               1179 //C
#define FID_ZSZBL1              1180 //C
#define FID_ZSZBL2              1181 //C
#define FID_QCKHS               1182 //C
#define FID_QMKHS               1183 //C
#define FID_KSHSL               1184 //C
#define FID_EN_ZQDM             1185 //C
#define FID_XCMRJ               1186 //C
#define FID_XCMCJ               1187 //C
#define FID_XHMRJ               1188 //C
#define FID_XHMCJ               1189 //C
#define FID_GSBL                1190 //C
#define FID_HLBZ                1191 //C
#define FID_DRCKJE              1192 //C
#define FID_TZCKJE              1193 //C
#define FID_JGMC_E              1194 //C
#define FID_FRDB                1195 //C
#define FID_WTQR                1196 //C
#define FID_HYLB                1197 //C
#define FID_YWFW                1198 //C
#define FID_ZCDZ                1199 //C
#define FID_ZCZB                1200 //C
#define FID_ZCYE                1201 //C
#define FID_FZYE                1202 //C
#define FID_YSZC                1203 //C
#define FID_CXWTH               1204 //C
#define FID_YWXZ                1205 //C
#define FID_SJXM                1206 //C
#define FID_SJMC                1207 //C
#define FID_JS                  1208 //C
#define FID_CCJJ                1209 //C
#define FID_LJYK                1210 //C
#define FID_PGSL                1211 //C
#define FID_BL                  1212 //C
#define FID_CSLB                1213 //C
#define FID_FJBZ                1214 //C
#define FID_QZQKBZ              1215 //C
#define FID_SBRQ                1216 //C
#define FID_ZCXX                1217 //C
#define FID_ZCSX                1218 //C
#define FID_TIME                1219 //C
#define FID_PGJE                1220 //C
#define FID_TGZH                1221 //C
#define FID_GZQX                1222 //C
#define FID_HGTS                1223 //C
#define FID_GZJYSX              1224 //C
#define FID_ISLOGIN             1225 //C
#define FID_GZNBDM              1226 //C
#define FID_GZFJSX              1227 //C
#define FID_GZMZSX              1228 //C
#define FID_GZJXTS              1229 //C
#define FID_FXJG                1230 //C
#define FID_TGBH                1231 //C
#define FID_DYSL                1232 //C
#define FID_TGRQ                1233 //C
#define FID_SXF                 1234 //C
#define FID_DJSL                1235 //C
#define FID_CQDJ                1236 //C
#define FID_JYFY                1237 //C
#define FID_DQBX                1238 //C
#define FID_GZLL                1239 //C
#define FID_DQRQ                1240 //C
#define FID_JXRQ                1241 //C
#define FID_LTRQ                1242 //C
#define FID_FXZQDJR             1243 //C
#define FID_ZQFXRQ              1244 //C
#define FID_DFZQDJR             1245 //C
#define FID_BRLX                1246 //C
#define FID_HGJG                1247 //C
#define FID_GHJG                1248 //C
#define FID_KTBZ                1249 //C
#define FID_HGSL                1250 //C
#define FID_HGRQ                1251 //C
#define FID_GHRQ                1252 //C
#define FID_ZRTGZH              1253 //C
#define FID_QTZC                1254 //C
#define FID_ZZC                 1255 //C
#define FID_WQSZJ               1256 //C
#define FID_JGDM                1257 //C
#define FID_DFSXFL              1258 //C
#define FID_DFLXSL              1259 //C
#define FID_JXFS                1260 //C
#define FID_CSSM                1261 //C
#define FID_SZSM                1262 //C
#define FID_XGGY                1263 //C
#define FID_LOGINNAME           1264 //C
#define FID_MRDLSF              1265 //C
#define FID_MGZC                1266 //C
#define FID_SNMGSY              1267 //C
#define FID_XZJB                1268 //C
#define FID_EN_MCQZ             1269 //C
#define FID_BDZQDM              1270 //C
#define FID_LYJBL               1271 //C
#define FID_RQWGHZJ             1272 //C
#define FID_RZWGHZJ             1273 //C
#define FID_BWJSZJ              1274 //C
#define FID_SWJSZJ              1275 //C
#define FID_YSYXYED             1276 //C
#define FID_DJWTK               1277 //C
#define FID_DJHBK               1278 //C
#define FID_CDSB                1279 //C
#define FID_CDQR                1280 //C
#define FID_WTQRNO              1281 //C
#define FID_CDQRNO              1282 //C
#define FID_TYPE_BF             1283 //C
#define FID_MODULE_BF           1284 //C
#define FID_HOST_BF             1285 //C
#define FID_WTSB_BF             1286 //C
#define FID_WTQR_BF             1287 //C
#define FID_CDSB_BF             1288 //C
#define FID_CDQR_BF             1289 //C
#define FID_WTQRNO_BF           1290 //C
#define FID_CDQRNO_BF           1291 //C
#define FID_TDBH                1292 //C
#define FID_EN_TDBH             1293 //C
#define FID_LTXW                1294 //C
#define FID_YYBXZMS             1295 //C
#define FID_ZQLBXZMS            1296 //C
#define FID_SBBS                1297 //C
#define FID_SBBS_S              1298 //C
#define FID_JGSJ                1299 //C
#define FID_YXHSBL1             1300 //C
#define FID_YXHSBL2             1301 //C
#define FID_ENDKHH              1302 //C
#define FID_FILESIZE            1303 //C
#define FID_FILETRANSIZE        1304 //C
#define FID_YJXX                1305 //C
#define FID_YJSX                1306 //C
#define FID_YHSL                1307 //C
#define FID_GHFL                1308 //C
#define FID_GHFXX               1309 //C
#define FID_GHFSX               1310 //C
#define FID_FJF                 1311 //C
#define FID_JSFL                1312 //C
#define FID_JSFXX               1313 //C
#define FID_JSFSX               1314 //C
#define FID_JYGFL               1315 //C
#define FID_JYGFXX              1316 //C
#define FID_JYGFSX              1317 //C
#define FID_QTFL                1318 //C
#define FID_QTFXX               1319 //C
#define FID_QTFSX               1320 //C
#define FID_FID                 1321 //C
#define FID_EN_XWH              1322 //C
#define FID_FWDM                1323 //C
#define FID_FWMC                1324 //C
#define FID_FWLX                1325 //C
#define FID_SLZ                 1326 //C
#define FID_CLFS                1327 //C
#define FID_FILE                1328 //C
#define FID_FILE2               1329 //C
#define FID_PROCNAME            1330 //C
#define FID_CSXH                1331 //C
#define FID_TYPE                1332 //C
#define FID_QSZ                 1333 //C
#define FID_CJHB                1334 //C
#define FID_CS1                 1335 //C
#define FID_CS2                 1336 //C
#define FID_CS3                 1337 //C
#define FID_CS4                 1338 //C
#define FID_CS5                 1339 //C
#define FID_CS6                 1340 //C
#define FID_CS7                 1341 //C
#define FID_CS8                 1342 //C
#define FID_CS9                 1343 //C
#define FID_CS10                1344 //C
#define FID_CS11                1345 //C
#define FID_CS12                1346 //C
#define FID_CS13                1347 //C
#define FID_CS14                1348 //C
#define FID_CS15                1349 //C
#define FID_OPTERATOR           1350 //C
#define FID_OPTION              1351 //C
#define FID_PACKINDEX           1352 //C
#define FID_GYDM                1353 //C
#define FID_JYJS                1354 //C
#define FID_QTSX                1355 //C
#define FID_TDJY                1356 //C
#define FID_MRJG5               1357 //C
#define FID_MRSL5               1358 //C
#define FID_MCJG5               1359 //C
#define FID_MCSL5               1360 //C
#define FID_ZQSZ_RMB            1361 //C
#define FID_ZQSZ_USD            1362 //C
#define FID_ZQSZ_HKD            1363 //C
#define FID_ZQSZ_ZSRMB          1364 //C
#define FID_ZJYE_RMB            1365 //C
#define FID_ZJYE_USD            1366 //C
#define FID_ZJYE_HKD            1367 //C
#define FID_ZJYE_ZSRMB          1368 //C
#define FID_QTZC_RMB            1369 //C
#define FID_QTZC_USD            1370 //C
#define FID_QTZC_HKD            1371 //C
#define FID_QTZC_ZSRMB          1372 //C
#define FID_LASTRECNO           1373 //C
#define FID_HTHQZFW             1374 //C
#define FID_TZZHDM              1375 //C
#define FID_TZZHMC              1376 //C
#define FID_TZZHQZ              1377 //C
#define FID_TZZHLB              1378 //C
#define FID_HTHQJ               1379 //C
#define FID_FWLB                1380 //C
#define FID_XMZX                1381 //C
#define FID_DZLB                1382 //C
#define FID_QSDZLB              1383 //C
#define FID_SJFY                1384 //C
#define FID_YJFY                1385 //C
#define FID_ZF                  1386 //C
#define FID_DF                  1387 //C
#define FID_FSCS                1388 //C
#define FID_HQNR                1389 //C
#define FID_ZDSJ                1390 //C
#define FID_SJQJ                1391 //C
#define FID_XWZBH               1392 //C
#define FID_XJDM                1393 //C
#define FID_RGDM                1394 //C
#define FID_RGQRDM              1395 //C
#define FID_XWZMC               1396 //C
#define FID_RIGH                1397 //C
#define FID_MGSY                1398 //C
#define FID_SHDM                1399 //C
#define FID_SZDM                1400 //C
#define FID_GSHY                1401 //C
#define FID_GSMC                1402 //C
#define FID_FXZL                1403 //C
#define FID_FILEWRITETIME       1404 //C
#define FID_DHXL                1405 //C
#define FID_BLFM                1406 //C
#define FID_BLFZ                1407 //C
#define FID_ZQL                 1408 //C
#define FID_SSGJ                1409 //C
#define FID_FXRQ                1410 //C
#define FID_ZQYHRQ              1411 //C
#define FID_CQRQ                1412 //C
#define FID_JKQSRQ              1413 //C
#define FID_JKJSRQ              1414 //C
#define FID_TSXX                1415 //C
#define FID_ZGB                 1416 //C
#define FID_MGGJJ               1417 //C
#define FID_MGWFPLR             1418 //C
#define FID_CLMC                1419 //C
#define FID_EN_FLLB             1420 //C
#define FID_GHFZKL              1421 //C
#define FID_LJJS                1422 //C
#define FID_LJZQ                1423 //C
#define FID_ZCJSFS              1424 //C
#define FID_ZSYJL               1425 //C
#define FID_JYLFDBH             1426 //C
#define FID_ZCFDBH              1427 //C
#define FID_JYLXX               1428 //C
#define FID_JYLSX               1429 //C
#define FID_GHJE                1430 //C
#define FID_FZYWDM              1431 //C
#define FID_LOGIN_ENABLE        1432 //C
#define FID_ZQJY_ENABLE         1433 //C
#define FID_ZJYW_ENABLE         1434 //C
#define FID_LSCXYW_ENABLE       1435 //C
#define FID_OFS_ENABLE          1436 //C
#define FID_KHYW_ENABLE         1437 //C
#define FID_SFYG                1438 //C
#define FID_XZYS                1439 //C
#define FID_FUNCID              1440 //C
#define FID_CXJE                1441 //C
#define FID_ZJLY                1442 //C
#define FID_WTSF                1443 //C
#define FID_CDSF                1444 //C
#define FID_XYSYBZ              1445 //C
#define FID_LSCLMS              1446 //C
#define FID_JLLSBZ              1447 //C
#define FID_TZMS                1448 //C
#define FID_DOMAIN1             1449 //C
#define FID_REGLOG              1450 //C
#define FID_SLTSFS              1451 //C
#define FID_OWNER_KH            1452 //C
#define FID_OWNER_JJR           1453 //C
#define FID_KZFS_KHQX           1454 //C
#define FID_KZFS_YHQX           1455 //C
#define FID_KZFS_CSQX           1456 //C
#define FID_KZFS_KHFL           1457 //C
#define FID_YXRQ                1458 //C
#define FID_WJLX                1459 //C
#define FID_WJLJ                1460 //C
#define FID_SYFW                1461 //C
#define FID_ZJDZ                1462 //C
#define FID_FXJB                1463 //C
#define FID_SQCZRH              1464 //C
#define FID_ZHGLJG              1465 //C
#define FID_ZJDZ_FRDB           1466 //C
#define FID_XM_JBR              1467 //C
#define FID_ZJLB_JBR            1468 //C
#define FID_ZJBH_JBR            1469 //C
#define FID_ZCFZ                1470 //C
#define FID_EN_ZCFZ             1471 //C
#define FID_XJYE                1472 //C
#define FID_RZRQ                1473 //C
#define FID_TXXS                1474 //C
#define FID_CDWZID_NEW          1475 //C
#define FID_KZYWDM              1476 //C
#define FID_KZYWMC              1477 //C
#define FID_KZYWSM              1478 //C
#define FID_KZYWZT              1479 //C
#define FID_ZZXY                1480 //C
#define FID_NZZCJE              1481 //C
#define FID_NZZRJE              1482 //C
#define FID_QTCKJE              1483 //C
#define FID_QTQKJE              1484 //C
#define FID_ZPCKJE              1485 //C
#define FID_ZPQKJE              1486 //C
#define FID_ZZZCJE              1487 //C
#define FID_ZZZRJE              1488 //C
#define FID_HCJE                1489 //C
#define FID_LBJE                1490 //C
#define FID_TJZQ                1491 //C
#define FID_TJDW                1492 //C
#define FID_TGZRHS              1493 //C
#define FID_TGZCHS              1494 //C
#define FID_TGZRSZ              1495 //C
#define FID_TGZCSZ              1496 //C
#define FID_ZDZRSZ              1497 //C
#define FID_CZZCSZ              1498 //C
#define FID_JGLBMC              1499 //C
#define FID_FXLB                1500 //C
#define FID_FXRDM               1501 //C
#define FID_QZDM                1502 //C
#define FID_QZLX                1503 //C
#define FID_XQBL                1504 //C
#define FID_FILEDATA            1505 //C
#define FID_FILEZIP             1506 //C
#define FID_FILECOMPANYNAME     1507 //C
#define FID_FILEPRODUCTNAME     1508 //C
#define FID_FILEDIR             1509 //C
#define FID_FILENEW             1510 //C
#define FID_FILERELATION        1511 //C
#define FID_FILEPOSITION        1512 //C
#define FID_FILETYPE            1513 //C
#define FID_XQDM                1514 //C
#define FID_XQFS                1515 //C
#define FID_XQJG                1516 //C
#define FID_ZCLB                1517 //C
#define FID_DBXS                1518 //C
#define FID_SJZD                1519 //C
#define FID_SRKJLX              1520 //C
#define FID_DZFS                1521 //C
#define FID_CXSL                1522 //C
#define FID_BLSFUNC             1523 //C
#define FID_QSFY                1524 //C
#define FID_RGRQ                1525 //C
#define FID_JGRQ                1526 //C
#define FID_JYSCPFL             1527 //C
#define FID_JYSCPZL             1528 //C
#define FID_DDLXXZ              1529 //C
#define FID_BSDDZXSL            1530 //C
#define FID_BSDDZXPLSL          1531 //C
#define FID_JYQX                1532 //C
#define FID_SBJB                1533 //C
#define FID_ZSXJ                1534 //C
#define FID_ISIN                1535 //C
#define FID_DDYXRQ              1536 //C
#define FID_DDSXXZ              1537 //C
#define FID_DDJYXZ              1538 //C
#define FID_JYSDDBH             1539 //C
#define FID_BRCJSL              1540 //C
#define FID_BRCJJE              1541 //C
#define FID_EN_SBJB             1542 //C
#define FID_DZXXBZ              1543 //C
#define FID_DXLX                1544 //C
#define FID_EN_LOGINID          1545 //C
#define FID_EN_JSDM             1546 //C
#define FID_JYBWFL              1547 //C
#define FID_QRSMJG              1548 //C
#define FID_HBSMJG              1549 //C
#define D_NONTRADINGORDTYPE     1550 //C
#define FID_ORDTYPE             1551 //C
#define FID_SIDE                1552 //C
#define FID_TIMEINFORCE         1553 //C
#define FID_TRADINGSESSIO       1554 //C
#define FID_XTCSBZ              1555 //C
#define FID_ZJJRBZ              1556 //C
#define FID_PJZC                1557 //C
#define FID_KHMMSQ              1558 //C
#define FID_TJRQ                1559 //C
#define FID_BCDJSL              1560 //C
#define FID_TQSL                1561 //C
#define FID_EN_SQLB             1562 //C
#define FID_RGJG                1563 //C
#define FID_RGSL                1564 //C
#define FID_CGLB                1565 //C
#define FID_CGZH                1566 //C
#define FID_CGYHDM              1567 //C
#define FID_CGYHZH              1568 //C
#define FID_CGCLJG              1569 //C
#define FID_CGJGSM              1570 //C
#define FID_CGCLRQ              1571 //C
#define FID_CGCLSJ              1572 //C
#define FID_CGWBCLJG            1573 //C
#define FID_CXWBLSH             1574 //C
#define FID_YHYE                1575 //C
#define FID_ZBYH                1576 //C
#define FID_CGJGDM              1577 //C
#define FID_MRSL6               1578 //C
#define FID_MRSL7               1579 //C
#define FID_MRSL8               1580 //C
#define FID_MRSL9               1581 //C
#define FID_MRSL10              1582 //C
#define FID_MCSL6               1583 //C
#define FID_MCSL7               1584 //C
#define FID_MCSL8               1585 //C
#define FID_MCSL9               1586 //C
#define FID_MCSL10              1587 //C
#define FID_MRJG6               1588 //C
#define FID_MRJG7               1589 //C
#define FID_MRJG8               1590 //C
#define FID_MRJG9               1591 //C
#define FID_MRJG10              1592 //C
#define FID_MCJG6               1593 //C
#define FID_MCJG7               1594 //C
#define FID_MCJG8               1595 //C
#define FID_MCJG9               1596 //C
#define FID_MCJG10              1597 //C
#define FID_PCDWBL              1598 //C
#define FID_MRJG                1599 //C
#define FID_TOKEN               1600 //C
#define FID_XYDJ                1601 //C
#define FID_CCSLXZ              1602 //C
#define FID_YJBL                1603 //C
#define FID_PCBL                1604 //C
#define FID_LTSL                1605 //C
#define FID_TABLENAME           1606 //C
#define FID_FIELDNAME           1607 //C
#define FID_JDBZ                1608 //C
#define FID_HYZ                 1609 //C
#define FID_HYB                 1610 //C
#define FID_JKHH                1611 //C
#define FID_DKHH                1612 //C
#define FID_JYYB                1613 //C
#define FID_DYYB                1614 //C
#define FID_ZCKZDX              1615 //C
#define FID_HYH                 1616 //C
#define FID_HYJE                1617 //C
#define FID_ZJZHBH              1618 //C
#define FID_RZLV                1619 //C
#define FID_JQRQ                1620 //C
#define FID_ZHYH                1621 //C
#define FID_JZJZH               1622 //C
#define FID_DZJZH               1623 //C
#define FID_JZJYYB              1624 //C
#define FID_DZJYYB              1625 //C
#define FID_EN_JYYB             1626 //C
#define FID_EN_DYYB             1627 //C
#define FID_EN_JZJYYB           1628 //C
#define FID_EN_DZJYYB           1629 //C
#define FID_DJGY                1630 //C
#define FID_SHGY                1631 //C
#define FID_JKHXM               1632 //C
#define FID_DKHXM               1633 //C
#define FID_EN_BH               1634 //C
#define FID_EN_ZBH              1635 //C
#define FID_ZHDYCS              1636 //C
#define FID_ZBH                 1637 //C
#define FID_ZHMC                1638 //C
#define FID_JZHYE               1639 //C
#define FID_DZHYE               1640 //C
#define FID_JZXSZ               1641 //C
#define FID_DZXSZ               1642 //C
#define FID_JZCZZ               1643 //C
#define FID_DZCZZ               1644 //C
#define FID_SHTG                1645 //C
#define FID_JQHYJE              1646 //C
#define FID_EN_KHYYB            1647 //C
#define FID_EN_ZJYYB            1648 //C
#define FID_SRYE2               1649 //C
#define FID_ZHYE2               1650 //C
#define FID_ZPJE2               1651 //C
#define FID_DJJE2               1652 //C
#define FID_YCDJJE2             1653 //C
#define FID_ZJCQDJ2             1654 //C
#define FID_WJSJE2              1655 //C
#define FID_KYZJ2               1656 //C
#define FID_KQZJ2               1657 //C
#define FID_XJZC2               1658 //C
#define FID_GPSZ2               1659 //C
#define FID_LX2                 1660 //C
#define FID_LXS2                1661 //C
#define FID_TZLX2               1662 //C
#define FID_RZJE2               1663 //C
#define FID_QSJE_B2             1664 //C
#define FID_QSJE_S2             1665 //C
#define FID_DRCKJE2             1666 //C
#define FID_TZCKJE2             1667 //C
#define FID_HAVE_ZCXX           1668 //C
#define FID_HAVE_JKCS           1669 //C
#define FID_XZDJ                1670 //C
#define FID_CCBLXZ              1671 //C
#define FID_ZHYJE               1672 //C
#define FID_RZJEBL              1673 //C
#define FID_RZBLSX              1674 //C
#define FID_SHQD                1675 //C
#define FID_YWDM                1676 //C
#define FID_SHFS                1677 //C
#define FID_SHJS                1678 //C
#define FID_LCMC                1679 //C
#define FID_SHJB                1680 //C
#define FID_LGFH                1681 //C
#define FID_HTSH                1682 //C
#define FID_LGFHJSDM            1683 //C
#define FID_JKYWDM              1684 //C
#define FID_SFJYLX              1685 //C
#define FID_MBMC                1686 //C
#define FID_XSBQ                1687 //C
#define FID_FLLB                1688 //C
#define FID_GFBDFX              1689 //C
#define FID_GFJSTS              1690 //C
#define FID_JHJJKS              1691 //C
#define FID_JHJJJS              1692 //C
#define FID_JJJYBZ              1693 //C
#define FID_JSFBZ               1694 //C
#define FID_JYZT                1695 //C
#define FID_JYKZ                1696 //C
#define FID_QSDZ                1697 //C
#define FID_SHSBBZ              1698 //C
#define FID_SZSBBZ              1699 //C
#define FID_SZCDBZ              1700 //C
#define FID_SWKSSJ              1701 //C
#define FID_SWBSSJ              1702 //C
#define FID_XWKSSJ              1703 //C
#define FID_XWBSSJ              1704 //C
#define FID_SJXZ                1705 //C
#define FID_XJFS                1706 //C
#define FID_ZJBDFX              1707 //C
#define FID_ZJJSTS              1708 //C
#define FID_XGDM                1709 //C
#define FID_PCKZ                1710 //C
#define FID_JSFS                1711 //C
#define FID_XWLX                1712 //C
#define FID_JGDW                1713 //C
#define FID_MCJG                1714 //C
#define FID_KCDW                1715 //C
#define FID_JYBM                1716 //C
#define FID_TZLB                1717 //C
#define FID_KPBZ                1718 //C
#define FID_RQJEBL              1719 //C
#define FID_BZJ                 1720 //C
#define FID_JYSBZJ              1721 //C
#define FID_JGSL                1722 //C
#define FID_LJZK                1723 //C
#define FID_FXL                 1724 //C
#define FID_ZFXL                1725 //C
#define FID_PCSL                1726 //C
#define FID_PCYK                1727 //C
#define FID_PCRQ                1728 //C
#define FID_CCWTH               1729 //C
#define FID_GSDM                1730 //C
#define FID_SBJLH               1731 //C
#define FID_ZKFY                1732 //C
#define FID_FHJE                1733 //C
#define FID_CJJJ                1734 //C
#define FID_DJBZJ               1735 //C
#define FID_SBGY                1736 //C
#define FID_BDJE                1737 //C
#define FID_BCDJ                1738 //C
#define FID_BDSJ                1739 //C
#define FID_CCSL                1740 //C
#define FID_BZJBL               1741 //C
#define FID_DWBZJ               1742 //C
#define FID_JYSBZJBL            1743 //C
#define FID_JYSDWBZJ            1744 //C
#define FID_LJFH                1745 //C
#define FID_BRSXF               1746 //C
#define FID_BRPCYK              1747 //C
#define FID_JYSBRSXF            1748 //C
#define FID_JYSCCXE             1749 //C
#define FID_KHCCXE              1750 //C
#define FID_SQCZBZ              1751 //C
#define FID_JSLB                1752 //C
#define FID_QXLB                1753 //C
#define FID_SHBZ                1754 //C
#define FID_AZRQ                1755 //C
#define FID_CPDM                1756 //C
#define FID_CPMC                1757 //C
#define FID_DFRQ                1758 //C
#define FID_XLH                 1759 //C
#define FID_YXXG                1760 //C
#define FID_ZJSQRQ              1761 //C
#define FID_CWJB                1762 //C
#define FID_JKLB                1763 //C
#define FID_JKCWDM              1764 //C
#define FID_CWLY                1765 //C
#define FID_KSKHH               1766 //C
#define FID_JSKHH               1767 //C
#define FID_KYKHH               1768 //C
#define FID_SJKZFS              1769 //C
#define FID_CPXM                1770 //C
#define FID_SJXZ_SQCZR          1771 //C
#define FID_TBTS_SQCZR          1772 //C
#define FID_ZJBH_SQCZR          1773 //C
#define FID_ZJLB_SQCZR          1774 //C
#define FID_JFQSRQ              1775 //C
#define FID_JGBZ                1776 //C
#define FID_KHJF                1777 //C
#define FID_KHKH                1778 //C
#define FID_MOBILE              1779 //C
#define FID_TZZFL               1780 //C
#define FID_YXZZDM              1781 //C
#define FID_ZDXM                1782 //C
#define FID_ZDZQ                1783 //C
#define FID_ZJDLRQ              1784 //C
#define FID_SXDM                1785 //C
#define FID_LQRQ                1786 //C
#define FID_JGXZ                1787 //C
#define FID_ZJLB_FRDB           1788 //C
#define FID_ZJBH_FRDB           1789 //C
#define FID_ZCSJ                1790 //C
#define FID_KHJLXM              1791 //C
#define FID_BZ1                 1792 //C
#define FID_BZ2                 1793 //C
#define FID_MBBH                1794 //C
#define FID_TABLE               1795 //C
#define FID_ACT                 1796 //C
#define FID_XZLB                1797 //C
#define FID_KHQZFW1             1798 //C
#define FID_SJYWKM              1799 //C
#define FID_LLLX                1800 //C
#define FID_RZJESX              1801 //C
#define FID_RQSLSX              1802 //C
#define FID_RZED                1803 //C
#define FID_RQED                1804 //C
#define FID_RZFDLL              1805 //C
#define FID_RQFDLL              1806 //C
#define FID_RZXYLL              1807 //C
#define FID_RQXYLL              1808 //C
#define FID_RQLL                1809 //C
#define FID_WYLB                1810 //C
#define FID_SQL                 1811 //C
#define FID_FILENAME            1812 //C
#define FID_FILEVERSION         1813 //C
#define FID_ZJLB_GDH            1814 //C
#define FID_MEMHEAD             1815 //C
#define FID_MEMDATA             1816 //C
#define FID_MEMCOUNT            1817 //C
#define FID_MEMSIZE             1818 //C
#define FID_GQZH_ZR             1819 //C
#define FID_PCCL                1820 //C
#define FID_RZXYED              1821 //C
#define FID_RQXYED              1822 //C
#define FID_RQJE                1823 //C
#define FID_YQSL                1824 //C
#define FID_RZSL                1825 //C
#define FID_RQSL                1826 //C
#define FID_RZWTSL              1827 //C
#define FID_RQWTSL              1828 //C
#define FID_RZWTJE              1829 //C
#define FID_RQWTJE              1830 //C
#define FID_RZCJSL              1831 //C
#define FID_RQCJSL              1832 //C
#define FID_RZCJJE              1833 //C
#define FID_RQCJJE              1834 //C
#define FID_YQWTSL              1835 //C
#define FID_YQCJSL              1836 //C
#define FID_HQWTSL              1837 //C
#define FID_HQCJSL              1838 //C
#define FID_RZLLXX              1839 //C
#define FID_RQLLXX              1840 //C
#define FID_RZXYJS              1841 //C
#define FID_RQXYJS              1842 //C
#define FID_RZXYLX              1843 //C
#define FID_RQXYLX              1844 //C
#define FID_RZYJLX              1845 //C
#define FID_RQYJLX              1846 //C
#define FID_FZJE                1847 //C
#define FID_FZSL                1848 //C
#define FID_MARGIN_ENABLE       1849 //C
#define FID_KQBZ                1850 //C
#define FID_KSSJ1               1851 //C
#define FID_JSSJ1               1852 //C
#define FID_KSSJ2               1853 //C
#define FID_JSSJ2               1854 //C
#define FID_WXWTFBZ             1855 //C
#define FID_MFCXCS              1856 //C
#define FID_KYXYED              1857 //C
#define FID_XYED                1858 //C
#define FID_RZFY                1859 //C
#define FID_RQFY                1860 //C
#define FID_BDKYZJ              1861 //C
#define FID_SHLX                1862 //C
#define FID_JCFL                1863 //C
#define FID_YSJYBZ              1864 //C
#define FID_YSKSSJ              1865 //C
#define FID_YSBSSJ              1866 //C
#define FID_JYSSXF              1867 //C
#define FID_YJL                 1868 //C
#define FID_YJLXX               1869 //C
#define FID_SLXX                1870 //C
#define FID_XMDM                1871 //C
#define FID_DAID                1872 //C
#define FID_INSINDEX            1873 //C
#define FID_MODINDEX            1874 //C
#define FID_LSHMC               1875 //C
#define FID_TRANPORT            1876 //C
#define FID_DATABASE            1877 //C
#define FID_DUMPPATH            1878 //C
#define FID_DUMPTYPE            1879 //C
#define FID_DUMPNOTE            1880 //C
#define FID_UPDATEITEM          1881 //C
#define FID_IDENTITY            1882 //C
#define FID_LOWPAR              1883 //C
#define FID_HIGHPAR             1884 //C
#define FID_CZYBH               1885 //C
#define FID_KHDDH               1886 //C
#define FID_QYLB                1887 //C
#define FID_TZRXM               1888 //C
#define FID_TZRLB               1889 //C
#define FID_JZJ                 1890 //C
#define FID_GDXM_OLD            1891 //C
#define FID_QQLB                1892 //C
#define FID_GDJC                1893 //C
#define FID_GFXZ                1894 //C
#define FID_PGDM                1895 //C
#define FID_XJFSMC              1896 //C
#define FID_XJLB                1897 //C
#define FID_WTRQ                1898 //C
#define FID_DYBZ                1899 //C
#define FID_BZXX                1900 //C
#define FID_TZRMC               1901 //C
#define FID_ZJBH_OLD            1902 //C
#define FID_TZRMC_OLD           1903 //C
#define FID_SBBZ                1904 //C
#define FID_CLSM                1905 //C
#define FID_CXLB                1906 //C
#define FID_XWH                 1907 //C
#define FID_KHHY                1908 //C
#define FID_SXZ_OLD             1909 //C
#define FID_TZRJC               1910 //C
#define FID_XB                  1911 //C
#define FID_DMQZ                1912 //C
#define FID_CSRQ                1913 //C
#define FID_MCQZ                1914 //C
#define FID_FRLB                1915 //C
#define FID_HYDM                1916 //C
#define FID_JSHY                1917 //C
#define FID_SDSL_GR             1918 //C
#define FID_SDSL_JG             1919 //C
#define FID_SRGDH               1920 //C
#define FID_SRXWH               1921 //C
#define FID_HBRQ                1922 //C
#define FID_YWLX                1923 //C
#define FID_WWMC                1924 //C
#define FID_TJSL                1925 //C
#define FID_SFJE                1926 //C
#define FID_DJGSSF              1927 //C
#define FID_DLJGSF              1928 //C
#define FID_SRZJBH              1929 //C
#define FID_SRGDXM              1930 //C
#define FID_SRDZ                1931 //C
#define FID_SRDH                1932 //C
#define FID_SRYZBM              1933 //C
#define FID_SRGFXZ              1934 //C
#define FID_DFXW                1935 //C
#define FID_DFGDH               1936 //C
#define FID_DFXZ                1937 //C
#define FID_QRBZ                1938 //C
#define FID_QQSL                1939 //C
#define FID_ZBQS                1940 //C
#define FID_GHSL                1941 //C
#define FID_DBQS                1942 //C
#define FID_GFXZSM              1943 //C
#define FID_QSLB                1944 //C
#define FID_QQSF_GR             1945 //C
#define FID_QQSF_JG             1946 //C
#define FID_QYZL                1947 //C
#define FID_ZBQSMC              1948 //C
#define FID_DYZQDM              1949 //C
#define FID_GHTS                1950 //C
#define FID_JXTS                1951 //C
#define FID_CLEARFEE            1952 //C
#define FID_FXJJFL              1953 //C
#define FID_ZGFL                1954 //C
#define FID_QTFLXX              1955 //C
#define FID_QTFLSX              1956 //C
#define FID_CJJEQD              1957 //C
#define FID_SFQD                1958 //C
#define FID_FJYRBS              1959 //C
#define FID_YEAR                1960 //C
#define FID_MBLB                1961 //C
#define FID_ZJDS                1962 //C
#define FID_ZCDS                1963 //C
#define FID_DJYHZHS             1964 //C
#define FID_FJXYXX              1965 //C
#define FID_FJYRZZBZ            1966 //C
#define FID_PGJG                1967 //C
#define FID_GSKYE               1968 //C
#define FID_JCGSKYE             1969 //C
#define FID_LXCZCS              1970 //C
#define FID_QDSJ                1971 //C
#define FID_QYZZBS              1972 //C
#define FID_ZJQDRQ              1973 //C
#define FID_KSWTH               1974 //C
#define FID_JSWTH               1975 //C
#define FID_KYWTH               1976 //C
#define FID_SQXQ                1977 //C
#define FID_SHZT                1978 //C
#define FID_SQGY                1979 //C
#define FID_SQRQ                1980 //C
#define FID_SQSJ                1981 //C
#define FID_HKQX                1982 //C
#define FID_MXTS                1983 //C
#define FID_YWSQH               1984 //C
#define FID_SHRQ                1985 //C
#define FID_SHSJ                1986 //C
#define FID_YMBBH               1987 //C
#define FID_XSXH                1988 //C
#define FID_MMTB                1989 //C
#define FID_EN_GYDM             1990 //C
#define FID_KHYYB               1991 //C
#define FID_NEWJJR              1992 //C
#define FID_ZPKZBZ              1993 //C
#define FID_DRCKKZ              1994 //C
#define FID_XML                 1995 //C
#define FID_QYDM                1996 //C
#define FID_QYSL                1997 //C
#define FID_QYJE                1998 //C
#define FID_JYRBS               1999 //C
#define FID_TIME_INIT           2000 //C
#define FID_TIME_CLOSE          2001 //C
#define FID_GQDJLSH             2002 //C
#define FID_LDSMJG              2003 //C
#define FID_XCXZBS              2004 //C
#define FID_EN_WTLB             2005 //C
#define FID_FXJ                 2006 //C
#define FID_GQDM                2007 //C
#define FID_GQLB                2008 //C
#define FID_GQLBMC              2009 //C
#define FID_GQMC                2010 //C
#define FID_GQSL                2011 //C
#define FID_GQZH                2012 //C
#define FID_JMC_ZDCGSL          2013 //C
#define FID_KSGQZH              2014 //C
#define FID_KYGQZH              2015 //C
#define FID_KZSX                2016 //C
#define FID_SDLX                2017 //C
#define FID_ROWNUM              2018 //C
#define FID_ZDCGSL              2019 //C
#define FID_ZSBJFD              2020 //C
#define FID_ZSQBJFD             2021 //C
#define FID_EN_GQDM             2022 //C
#define FID_EN_GQLB             2023 //C
#define FID_GZMZ                2024 //C
#define FID_FXDS                2025 //C
#define FID_MRED                2026 //C
#define FID_MCED                2027 //C
#define FID_PXCS                2028 //C
#define FID_URL                 2029 //C
#define FID_ZSR                 2030 //C
#define FID_ZLR                 2031 //C
#define FID_JLR                 2032 //C
#define FID_MGFH                2033 //C
#define FID_FHHJZC              2034 //C
#define FID_MGJZC               2035 //C
#define FID_PAY                 2036 //C
#define FID_DZ_OFFICE           2037 //C
#define FID_ZZJGDM              2038 //C
#define FID_SFJE_GR             2039 //C
#define FID_SFJE_JG             2040 //C
#define FID_KHH_YJ              2041 //C
#define FID_GQZH_YJ             2042 //C
#define FID_SXF_ZR              2043 //C
#define FID_ZDHBSL              2044 //C
#define FID_ZDCFSL              2045 //C
#define FID_RZSYLLFD            2046 //C
#define FID_RQSYLLFD            2047 //C
#define FID_RZEDLLFD            2048 //C
#define FID_RQEDLLFD            2049 //C
#define FID_ZDCXRQ              2050 //C
#define FID_WEEK                2051 //C
#define FID_MILLISECOND         2052 //C
#define FID_GDSL                2053 //C
#define FID_CCSLXZ_JG           2054 //C
#define FID_CCSLXZ_ZG           2055 //C
#define FID_JYJS_GR_ZGG         2056 //C
#define FID_JYJS_GR_TZG         2057 //C
#define FID_JYJS_JG_ZGG         2058 //C
#define FID_JYJS_JG_TZG         2059 //C
#define FID_ZGBZ                2060 //C
#define FID_QYDJRQ              2061 //C
#define FID_KHH_ZQR             2062 //C
#define FID_GQZH_ZQR            2063 //C
#define FID_SXF_ZQR             2064 //C
#define FID_GFXZ_YJ             2065 //C
#define FID_RZXYED_OLD          2067 //C
#define FID_RQXYED_OLD          2068 //C
#define FID_EN_JGDM             2069 //C
#define FID_EX_JGDM             2070 //C
#define FID_NODEID              2071 //C
#define FID_NODENAME            2072 //C
#define FID_SEAT_SH             2073 //C
#define FID_SEAT_SZ             2074 //C
#define FID_ADDR_IP             2075 //C
#define FID_ADDR_MAC            2076 //C
#define FID_OID                 2077 //C
#define FID_LOG_POS             2078 //C
#define FID_INDEX               2079 //C
#define FID_KSSBWTH             2080 //C
#define FID_DZJGSX              2081 //C
#define FID_DZJGXX              2082 //C
#define FID_ZCJSL               2083 //C
#define FID_QTZGCCSX            2090 //C
#define FID_QTJGCCXX            2091 //C
#define FID_OFSS_JZ             2100 //C
#define FID_WJBM                2201 //C
#define FID_WJMC                2202 //C
#define FID_WJHM                2203 //C
#define FID_TMHM                2204 //C
#define FID_TMLX                2205 //C
#define FID_TMMS                2206 //C
#define FID_TMDA                2207 //C
#define FID_SCORE               2208 //C
#define FID_ZJYXQ               2209 //C
#define FID_ZJDZYB              2210 //C
#define FID_ZJFZJG              2211 //C
#define FID_EDZ                 2212 //C
#define FID_YYZZNJRQ            2213 //C
#define FID_JTDZ                2214 //C
#define FID_JTYB                2215 //C
#define FID_QTDH                2216 //C
#define FID_QQ                  2217 //C
#define FID_FXQHYLB             2218 //C
#define FID_XQFXDJ              2219 //C
#define FID_FXQSZRQ             2220 //C
#define FID_HYZK                2221 //C
#define FID_JG                  2222 //C
#define FID_MZDM                2223 //C
#define FID_GZDW                2224 //C
#define FID_GZDWDZ              2225 //C
#define FID_GZDWYB              2226 //C
#define FID_GZDWZW              2227 //C
#define FID_GZDWDH              2228 //C
#define FID_FXCSNL              2229 //C
#define FID_FXPGRQ              2230 //C
#define FID_JJFXCSNL            2231 //C
#define FID_JJFXPGRQ            2232 //C
#define FID_GPFXCSNL            2233 //C
#define FID_GPFXPGRQ            2234 //C
#define FID_XYFXCSNL            2235 //C
#define FID_XYFXPGRQ            2236 //C
#define FID_KHKZT               2237 //C
#define FID_TBSM                2238 //C
#define FID_ZZSHZT              2239 //C
#define FID_GSDH                2240 //C
#define FID_ZCRQ                2241 //C
#define FID_LTGB                2242 //C
#define FID_ZZJGDMYXQ           2243 //C
#define FID_ZZJGDMFZJG          2244 //C
#define FID_ZZJGDMNJRQ          2245 //C
#define FID_SWDJZ               2246 //C
#define FID_SWDJZYXQ            2247 //C
#define FID_SWDJZFZJG           2248 //C
#define FID_SWDJZNJRQ           2249 //C
#define FID_ZJYXQ_FRDB          2250 //C
#define FID_ZJYXQ_JBR           2251 //C
#define FID_DH_JBR              2252 //C
#define FID_MOBILE_JBR          2253 //C
#define FID_XB_JBR              2254 //C
#define FID_FWMM                2255 //C
#define FID_HXKH                2256 //C
#define FID_HGDM                2300 //C
#define FID_HGMC                2301 //C
#define FID_DQLL                2302 //C
#define FID_TQLL                2303 //C
#define FID_ZED                 2304 //C
#define FID_ZYED                2305 //C
#define FID_DEBS                2306 //C
#define FID_TQGHSX              2307 //C
#define FID_GXRQ                2308 //C
#define FID_GDFJQX              2309 //C
#define FID_ZDXY                2310 //C
#define FID_SX1                 2311 //C
#define FID_SX2                 2312 //C
#define FID_HGED                2313 //C
#define FID_YYLB                2314 //C
#define FID_XYTS                2315 //C
#define FID_TQXZBL              2316 //C
#define FID_YYTQTS              2317 //C
#define FID_XZBL                2318 //C
#define FID_TQYYSX              2319 //C
#define FID_JZSJ                2320 //C
#define FID_SYBDBL              2321 //C
#define FID_TQYYDBQS            2322 //C
#define FID_TQDBSX              2323 //C
#define FID_CZRBM               2502 //C
#define FID_CZRMC               2503 //C
#define FID_ZQRBM               2504 //C
#define FID_ZQRMC               2505 //C
#define FID_ZYHYBH              2506 //C
#define FID_DKHYBH              2507 //C
#define FID_DKJE                2508 //C
#define FID_DKDQRQ              2509 //C
#define FID_HTDJRQ              2510 //C
#define FID_WTZT                2514 //C
#define FID_ZYZH                2522 //C
#define FID_DJBH                2523 //C
#define FID_SBLSH               2524 //C
#define FID_ZQMZ                2525 //C
#define FID_FU_HYQY             2600 //C
#define FID_CZMM                3002 //C
#define FID_TXMM                3004 //C
#define FID_GTKHLB              3006 //C
#define FID_ROUTER              3007 //C
#define FID_ENTRY               3008 //C
#define FID_KHHQZ               3009 //C
#define FID_CHECKBOX            3010 //C
#define FID_CZLB                3011 //C
#define FID_PUSH                3021 //C
#define FID_ZJBL                3022 //C
#define FID_HQZD                3023 //C
#define FID_ZDF                 3024 //C
#define FID_HQZF                3027 //C
#define FID_HSL                 3028 //C
#define FID_ICON                3029 //C
#define FID_FZDM                3030 //C
#define FID_FZMC                3031 //C
#define FID_HFBH                3032 //C
#define FID_FSKHH               3033 //C
#define FID_FSFJBZ              3034 //C
#define FID_DFKHH               3035 //C
#define FID_STATE               3036 //C
#define FID_DLSJ                3037 //C
#define FID_QTSJ                3038 //C
#define FID_MLLB                3040 //C
#define FID_MLBM                3041 //C
#define FID_MLMC                3042 //C
#define FID_MLSM                3043 //C
#define FID_FORMAT              3044 //C
#define FID_DEFAULT             3045 //C
#define FID_DATA                3046 //C
#define FID_JLBZ                3047 //C
#define FID_MBSMS               3050 //C
#define FID_MBMAIL              3051 //C
#define FID_LBMC                3053 //C
#define FID_CSLX                3054 //C
#define FID_XMMC                3060 //C
#define FID_FWXZ                3061 //C
#define FID_RECNO               3062 //C
#define FID_YJB                 3063 //C
#define FID_CCMAIL              3064 //C
#define FID_YJXM                3065 //C
#define FID_PRODUCT             3071 //C
#define FID_VERSION             3072 //C
#define FID_COMPANY             3073 //C
#define FID_LWTIME              3075 //C
#define FID_PKLEN               3076 //C
#define FID_PACKAGE             3077 //C
#define FID_SUBDIR              3078 //C
#define FID_ZHBZ                3081 //C
#define FID_IBY                 3082 //C
#define FID_BYDZ1               3085 //C
#define FID_BYDZ2               3086 //C
#define FID_BYDZ3               3087 //C
#define FID_XH                  3090 //C
#define FID_DXFDED              3107 //C
#define FID_YJFDED              3108 //C
#define FID_DXFYBL              3109 //C
#define FID_YJFYBL              3110 //C
#define FID_YXSJ                3113 //C
#define FID_LYLX                3114 //C
#define FID_KTZT                3115 //C
#define FID_YWSM                3116 //C
#define FID_WTFSDM              3200 //C
#define FID_PRIVATEKEY          3202 //C
#define FID_DEVICENAME          3800 //C
#define FID_DATANAME            3801 //C
#define FID_DATASIZE            3802 //C
#define FID_DEVICESIZE          3803 //C
#define FID_YJBCDM              3804 //C
#define FID_MINIMAGESIZE        3839 //C
#define FID_MAXIMAGESIZE        3840 //C
#define FID_ALERTIMAGESIZE      3841 //C
#define FID_QZYZFS              3900 //C
#define FID_KXYZFS              3901 //C
#define FID_YZFS_SQCZR          3902 //C
#define FID_APPID               4001 //C
#define FID_BCJJSL              4002 //C
#define FID_BGFHFS              4003 //C
#define FID_BKKBZ               4004 //C
#define FID_BRBZS1              4005 //C
#define FID_BRCKJE              4006 //C
#define FID_BRCXZD              4007 //C
#define FID_BRZDJY              4008 //C
#define FID_CBJ                 4009 //C
#define FID_CDYWLB              4010 //C
#define FID_CFBL                4011 //C
#define FID_CFBZ                4012 //C
#define FID_CFGDM               4013 //C
#define FID_CFGSL               4014 //C
#define FID_CJHBNO              4015 //C
#define FID_DFBZ                4016 //C
#define FID_DFDJSL              4017 //C
#define FID_DFJGDM              4018 //C
#define FID_DFJSDM              4019 //C
#define FID_DFJSJG              4020 //C
#define FID_DFJSLX              4021 //C
#define FID_DFJSZH              4022 //C
#define FID_DFKHQZ              4023 //C
#define FID_DFLOGINID           4024 //C
#define FID_DFWJSSL             4025 //C
#define FID_DFWZDM              4026 //C
#define FID_DFYHDM              4027 //C
#define FID_DFYHZH              4028 //C
#define FID_DFYWKM              4029 //C
#define FID_DFYZBM              4030 //C
#define FID_DFZJBH              4031 //C
#define FID_DFZJLB              4032 //C
#define FID_DFZJZH              4033 //C
#define FID_DFZQDM              4034 //C
#define FID_DFZQSL              4035 //C
#define FID_DFZY                4036 //C
#define FID_DJYE                4037 //C
#define FID_DJYXRQ              4038 //C
#define FID_DLCS                4039 //C
#define FID_DLKZFS              4040 //C
#define FID_DLSFBZ              4041 //C
#define FID_DLSFFW              4042 //C
#define FID_DLSFJE              4043 //C
#define FID_DLSFSX              4044 //C
#define FID_DZLXS               4045 //C
#define FID_EDKZBZ              4046 //C
#define FID_EN_CJHBNO           4047 //C
#define FID_EN_FXDJ             4048 //C
#define FID_EN_GFXZ             4049 //C
#define FID_EN_JDBM             4050 //C
#define FID_EN_JJDM             4051 //C
#define FID_EN_JYQX             4052 //C
#define FID_EN_SFFS             4053 //C
#define FID_EN_WTFL             4054 //C
#define FID_EN_WTHQZ            4055 //C
#define FID_EN_YHDM             4056 //C
#define FID_EN_YWDM             4057 //C
#define FID_FHDM                4058 //C
#define FID_FHDWJE              4059 //C
#define FID_FILEID              4060 //C
#define FID_FJYRJYBZ            4061 //C
#define FID_FLSX                4062 //C
#define FID_FWFL                4063 //C
#define FID_FWFSX               4064 //C
#define FID_FWFXX               4065 //C
#define FID_FXBL                4066 //C
#define FID_FXPP                4068 //C
#define FID_GRZDSCRGSG          4069 //C
#define FID_GRZDZJRGSG          4070 //C
#define FID_GRZGDTSH            4071 //C
#define FID_HBJG                4072 //C
#define FID_HGBZ                4073 //C
#define FID_HISTORY             4074 //C
#define FID_HLSYTS              4075 //C
#define FID_HQCXCS              4077 //C
#define FID_HQMFCS              4078 //C
#define FID_HQSFBZ              4079 //C
#define FID_HQSFJE              4080 //C
#define FID_HS                  4081 //C
#define FID_HZSJ                4082 //C
#define FID_INI                 4083 //C
#define FID_JBQXLB              4084 //C
#define FID_JFSJ                4086 //C
#define FID_JGZDSCRGSG          4087 //C
#define FID_JGZDZJRGSG          4088 //C
#define FID_JGZGDTSH            4089 //C
#define FID_JJCFZT              4090 //C
#define FID_JJHBZT              4091 //C
#define FID_JJKHZT              4092 //C
#define FID_JJRGZT              4093 //C
#define FID_JJSGZT              4094 //C
#define FID_JJSHZT              4095 //C
#define FID_JJZHSQFS            4096 //C
#define FID_JJZHSX              4097 //C
#define FID_JJZHZT              4098 //C
#define FID_JSBZ                4099 //C
#define FID_JSKZFS              4100 //C
#define FID_JSSFBZ              4101 //C
#define FID_JSSFDW              4102 //C
#define FID_JSSFJE              4103 //C
#define FID_JSSFQD              4104 //C
#define FID_JSSFSX              4105 //C
#define FID_JSSJSX              4106 //C
#define FID_JXJE                4107 //C
#define FID_JYJ                 4108 //C
#define FID_JYLBSX              4109 //C
#define FID_JYLTJFS             4110 //C
#define FID_JYSQH               4111 //C
#define FID_KHFL                4112 //C
#define FID_KHXMXY              4113 //C
#define FID_KWTSL               4114 //C
#define FID_TJZC                4115 //C
#define FID_LLMBBH              4116 //C
#define FID_MCCJJE              4117 //C
#define FID_MCCJSL              4118 //C
#define FID_MCQSJE              4119 //C
#define FID_MCWTJE              4120 //C
#define FID_MCWTSL              4121 //C
#define FID_MMBDRQ              4122 //C
#define FID_MMXZFS              4123 //C
#define FID_MRCJJE              4124 //C
#define FID_MRCJSL              4125 //C
#define FID_MRFHFS              4126 //C
#define FID_MRQSJE              4127 //C
#define FID_MRWTJE              4128 //C
#define FID_MRWTSL              4129 //C
#define FID_MXBZ                4130 //C
#define FID_ORDWTH              4131 //C
#define FID_OTHER               4132 //C
#define FID_PHRQ                4133 //C
#define FID_POSITION            4134 //C
#define FID_QRLSH               4135 //C
#define FID_QSRQ                4136 //C
#define FID_QTDJ                4137 //C
#define FID_QTFY                4138 //C
#define FID_QTMM                4139 //C
#define FID_QXSX                4140 //C
#define FID_QYRQ                4141 //C
#define FID_RGSGJS              4142 //C
#define FID_RQJS                4143 //C
#define FID_RZBZ                4144 //C
#define FID_RZJS                4145 //C
#define FID_S7                  4146 //C
#define FID_SBFS                4147 //C
#define FID_SFSX                4148 //C
#define FID_SGSHDM              4149 //C
#define FID_SMBS                4150 //C
#define FID_SPBZ                4151 //C
#define FID_SRRQ                4152 //C
#define FID_STAMP               4153 //C
#define FID_SXFSX               4154 //C
#define FID_SXFXX               4155 //C
#define FID_SXYK                4156 //C
#define FID_T3JS                4157 //C
#define FID_TABM                4158 //C
#define FID_TAKZSX              4159 //C
#define FID_TEST                4160 //C
#define FID_THREAD              4161 //C
#define FID_TSYWJSSJ            4162 //C
#define FID_TXDZ                4163 //C
#define FID_TXTS                4164 //C
#define FID_WJSSL_B             4165 //C
#define FID_WJSSL_S             4166 //C
#define FID_WTBZ                4167 //C
#define FID_WTDJJE              4168 //C
#define FID_WTHQZ               4169 //C
#define FID_WTMARK              4170 //C
#define FID_WZDM                4171 //C
#define FID_XSSL                4172 //C
#define FID_XTZT                4173 //C
#define FID_XYZT                4174 //C
#define FID_XZFS                4175 //C
#define FID_YDH                 4176 //C
#define FID_YGXJCE              4177 //C
#define FID_YHKZSX              4178 //C
#define FID_YWBS                4179 //C
#define FID_YWRQ                4180 //C
#define FID_YYBBH               4181 //C
#define FID_ZCSMJG              4182 //C
#define FID_ZCTJFS              4183 //C
#define FID_ZCZQSZ              4184 //C
#define FID_ZDHS                4185 //C
#define FID_ZJBHXY              4186 //C
#define FID_ZJDM                4187 //C
#define FID_ZJSBSJ              4188 //C
#define FID_ZQFXDJ              4189 //C
#define FID_ZQJCLB              4190 //C
#define FID_ZQJYSX              4191 //C
#define FID_ZQLBXZFS            4192 //C
#define FID_ZQSXFW              4193 //C
#define FID_ZQXZMS              4194 //C
#define FID_ZQYWDM              4195 //C
#define FID_ZRZQSZ              4196 //C
#define FID_ZYQDM               4197 //C
#define FID_ZZKSSJ              4198 //C
#define FID_ZZLB                4199 //C
#define FID_ZZQDM               4200 //C
#define FID_LTLX                4201 //C
#define FID_BBFUNCID            4202 //C
#define FID_BBBSC               4203 //C
#define FID_BBSORTTYPE          4204 //C
#define FID_BBCXLB              4205 //C
#define FID_BBFIELDNAME         4206 //C
#define FID_BBTYPE              4207 //C
#define FID_BBVALUE             4208 //C
#define FID_BBROWNUM            4209 //C
#define FID_BBSJJDM             4210 //C
#define FID_JYRQ                4211 //C
#define FID_TDLX_BF             4212 //C
#define FID_SGWTSL              4213 //C
#define FID_DFJDBM              4214 //C
#define FID_ID                  9001 //C
#define FID_MODULE              9002 //C
#define FID_NAME                9003 //C
#define FID_CLASE               9004 //C
#define FID_LEVEL               9006 //C
#define FID_OLDVER              9007 //C
#define FID_LASTVER             9008 //C
#define FID_WHYS                9009 //C
#define FID_FILEPATH            9011 //C
#define FID_MENDER              9012 //C
#define FID_CONNER              9013 //C
#define FID_MODIRQ              9014 //C
#define FID_TESTRQ              9015 //C
#define FID_CONCLUSION          9016 //C
#define FID_UPNOTE              9017 //C
#define FID_STATUS              9018 //C
#define FID_RESOLVEN            9019 //C
#define FID_FLAG                9020 //C
#define FID_DIFF                9021 //C
#define FID_YZJB                9022 //C
#define FID_RWBH                9023 //C
#define FID_DIR                 9024 //C
#define FID_CPID                9025 //C
#define FID_XQLX                9026 //C
#define FID_XQLY                9027 //C
#define FID_XQMS                9028 //C
#define FID_XQLXF               9029 //C
#define FID_XGFA                9030 //C
#define FID_FASP                9031 //C
#define FID_FASPRQ              9032 //C
#define FID_JRX                 9033 //C
#define FID_FFJH                9034 //C
#define FID_XGR                 9035 //C
#define FID_XGJD                9036 //C
#define FID_CSR                 9037 //C
#define FID_CSJD                9038 //C
#define FID_YMTS                9039 //C
#define FID_XGFK                9040 //C
#define FID_XGWCRQ              9041 //C
#define FID_CSFK                9042 //C
#define FID_CSWCRQ              9043 //C
#define FID_HFYJ                9044 //C
#define FID_HFRQ                9045 //C
#define FID_HFR                 9046 //C
#define FID_RWB                 9047 //C
#define FID_MTYPE               9048 //C
#define FID_GYXM                9049 //C
#define FID_JLZ                 9050 //C
#define FID_GH                  9051 //C
#define FID_KHMC                9052 //C
#define FID_WHR                 9053 //C
#define FID_XZR                 9054 //C
#define FID_KHID                9055 //C
#define FID_WTMS                9056 //C
#define FID_FXDW                9057 //C
#define FID_JJFS                9058 //C
#define FID_JJGC                9059 //C
#define FID_CLYS                9060 //C
#define FID_FSRQ                9061 //C
#define FID_WTFL                9062 //C
#define FID_GROUP               9063 //C
#define FID_SECURITY            9064 //C
#define FID_GXQ                 9065 //C
#define FID_CPXX                9066 //C
#define FID_KHZB                9067 //C
#define FID_QYZB                9068 //C
#define FID_ZJL                 9070 //C
#define FID_ZJLDH               9071 //C
#define FID_ZJLMAIL             9072 //C
#define FID_JL                  9073 //C
#define FID_JLDH                9074 //C
#define FID_JLMAIL              9075 //C
#define FID_LXR                 9076 //C
#define FID_CRDATE              9077 //C
#define FID_ENGINEERS           9078 //C
#define FID_HFRQ2               9079 //C
#define FID_DJR                 9080 //C
#define FID_ZW                  9081 //C
#define FID_WHBT                9082 //C
#define FID_FLAG1               9083 //C
#define FID_FLAG2               9084 //C
#define FID_XQLB                9085 //C
#define FID_MSN                 9086 //C
#define FID_SPFA                9087 //C
#define FID_SJNR                9088 //C
#define FID_LCRZ                9089 //C
#define FID_SPR                 9090 //C
#define FID_SPRQ                9091 //C
#define FID_GZR                 9092 //C
#define FID_XQBT                9093 //C
#define FID_ZPR                 9094 //C
#define FID_RWMS                9095 //C
#define FID_ZPRQ                9096 //C
#define FID_GMZQ                9097 //C
#define FID_GYZT                9098 //C
#define FID_KSSJ                9099 //C
#define FID_JSSJ                9100 //C
#define FID_XZQYDM              9101 //C
#define FID_XZQYMC              9102 //C
#define FID_XZQYLB              9103 //C
#define FID_SJXZQYDM            9104 //C
#define FID_DHQH                9105 //C
#define FID_KHBS                9106 //C
#define FID_KHZT                9107 //C
#define FID_ZT                  9108 //C
#define FID_SORTTYPE            9109 //C
#define FID_ROWCOUNT            9110 //C
#define FID_LPDM                9111 //C
#define FID_YWSHBZ              9112 //C
#define FID_YWSHQD              9113 //C
#define FID_LPZCDS              9114 //C
#define FID_SRJE                9115 //C
#define FID_FCJE                9116 //C
#define FID_CZBZ                9117 //C
#define FID_JSJ                 9118 //C
#define FID_YSJE_YJ             9119 //C
#define FID_JGZLLB              9120 //C
#define FID_S11                 9121 //C
#define FID_S12                 9122 //C
#define FID_S13                 9123 //C
#define FID_S15                 9124 //C
#define FID_S16                 9125 //C
#define FID_BZQDM               9126 //C
#define FID_CWLB                9127 //C
#define FID_YHMM                9128 //C
#define FID_JJDM                9129 //C
#define FID_JJMC                9130 //C
#define FID_XJTDBL              9131 //C
#define FID_WTJE                9132 //C
#define FID_SGSHZT              9133 //C
#define FID_TDBZ                9134 //C
#define FID_ZDXW                9135 //C
#define FID_XJCE                9136 //C
#define FID_TDJE                9137 //C
#define FID_DWJZ                9138 //C
#define FID_SGSHDWJZ            9139 //C
#define FID_CZGY                9140 //C
#define FID_FYBL                9141 //C
#define FID_JYL                 9142 //C
#define FID_XGPZ                9143 //C
#define FID_XGZH                9144 //C
#define FID_JESX                9145 //C
#define FID_FSSL                9146 //C
#define FID_LXJE                9147 //C
#define FID_LXJG                9148 //C
#define FID_PLWTPCH             9149 //C
#define FID_SEQNO               9150 //C
#define FID_SBXW                9151 //C
#define FID_XWDM                9152 //C
#define FID_EN_JGZLLB           9153 //C
#define FID_WBJGDM              9154 //C
#define FID_WBFJJYLB            9155 //C
#define FID_CZWBSQBH            9156 //C
#define FID_WBSQBH              9157 //C
#define FID_RWSM                9158 //C
#define FID_FHRQ                9159 //C
#define FID_FLLBFW              9160 //C
#define FID_JYSFW               9161 //C
#define FID_SDSL                9162 //C
#define FID_WTFSFW              9163 //C
#define FID_ZDJSBZ              9164 //C
#define FID_JYLBFW              9165 //C
#define FID_TJZQS               9166 //C
#define FID_JJZHCD              9167 //C
#define FID_JYMCD               9168 //C
#define FID_SQBHCD              9169 //C
#define FID_JJZHSCFS            9170 //C
#define FID_JYZHQZ              9171 //C
#define FID_KYJJZH_GR           9172 //C
#define FID_KYJJZH_JG           9173 //C
#define FID_FEDZZT              9174 //C
#define FID_HBDZBZ              9175 //C
#define FID_FEDZXM              9176 //C
#define FID_FEDZFS              9177 //C
#define FID_FJYGHLB             9178 //C
#define FID_JGSCRGZDZJ          9179 //C
#define FID_GRSCRGZDZJ          9180 //C
#define FID_GRZJRGZDZJ          9181 //C
#define FID_JGZJRGZDZJ          9182 //C
#define FID_GRZDRGZJ            9183 //C
#define FID_JGZDRGZJ            9184 //C
#define FID_GRSCSGZDZJ          9185 //C
#define FID_JGSCSGZDZJ          9186 //C
#define FID_GRZJSGZDZJ          9187 //C
#define FID_JGZJSGZDZJ          9188 //C
#define FID_GRSHZDFE            9189 //C
#define FID_JGSHZDFE            9190 //C
#define FID_GRCCZDFE            9191 //C
#define FID_JGCCZDFE            9192 //C
#define FID_SHSYTS              9193 //C
#define FID_HLHKTS              9194 //C
#define FID_GRZDZHFE            9195 //C
#define FID_JGZDZHFE            9196 //C
#define FID_SGJSBZ              9197 //C
#define FID_TADM                9198 //C
#define FID_FQRDM               9199 //C
#define FID_FXZFE               9200 //C
#define FID_GLRDM               9201 //C
#define FID_JJJC                9202 //C
#define FID_JJQC                9203 //C
#define FID_JJJZ                9204 //C
#define FID_DFJJDM              9205 //C
#define FID_RGFS                9206 //C
#define FID_RGJS                9207 //C
#define FID_SGJS                9208 //C
#define FID_TGRDM               9209 //C
#define FID_TDLX                9210 //C
#define FID_MODULE_ID           9211 //C
#define FID_ZKLX                9212 //C
#define FID_ZKL                 9213 //C
#define FID_DXBS                9214 //C
#define FID_DXLB                9215 //C
#define FID_BDKHBZ              9216 //C
#define FID_DJYY                9217 //C
#define FID_DZDLB               9219 //C
#define FID_YSQBH               9225 //C
#define FID_ZJJSLX              9226 //C
#define FID_YYRQ                9227 //C
#define FID_JJZH                9228 //C
#define FID_JJZHXM              9229 //C
#define FID_XSDM                9231 //C
#define FID_TJDM                9232 //C
#define FID_JJFL                9233 //C
#define FID_GRZGCYBL            9234 //C
#define FID_JGZGCYBL            9235 //C
#define FID_MRFS                9236 //C
#define FID_KYSL                9237 //C
#define FID_WTFE                9238 //C
#define FID_YYBZ                9239 //C
#define FID_ORDERS              9240 //C
#define FID_DFJJZH              9241 //C
#define FID_DFJYZH              9242 //C
#define FID_DFWDH               9243 //C
#define FID_DFXSSDM             9244 //C
#define FID_PZDM                9245 //C
#define FID_DFSFFS              9246 //C
#define FID_GHYY                9247 //C
#define FID_JJSL                9248 //C
#define FID_LJWYCS              9249 //C
#define FID_LXWYCS              9250 //C
#define FID_QQCS                9251 //C
#define FID_SCKKRQ              9252 //C
#define FID_MYKKRQ              9253 //C
#define FID_SGJE                9254 //C
#define FID_SCSGZDJE            9255 //C
#define FID_SGZDJE              9256 //C
#define FID_CONTENT             9257 //C
#define FID_TITLE               9258 //C
#define FID_GGLB                9259 //C
#define FID_JYZH                9260 //C
#define FID_TALSH               9261 //C
#define FID_QRRQ                9262 //C
#define FID_QRFE                9263 //C
#define FID_QRJE                9264 //C
#define FID_DLF                 9265 //C
#define FID_SHF                 9266 //C
#define FID_YHS                 9267 //C
#define FID_ZFE                 9268 //C
#define FID_DJFE                9269 //C
#define FID_KYFE                9270 //C
#define FID_DZRQ                9271 //C
#define FID_SFHLJE              9272 //C
#define FID_HLZJE               9273 //C
#define FID_FHDWFE              9274 //C
#define FID_FHJJFE              9275 //C
#define FID_ZTZFE               9276 //C
#define FID_DJZTZFE             9277 //C
#define FID_YJKBFS              9278 //C
#define FID_ZFHJE               9279 //C
#define FID_HGRQFCJE            9280 //C
#define FID_HGRZSRJE            9281 //C
#define FID_RQGHSRJE            9282 //C
#define FID_RZGHFCJE            9283 //C
#define FID_HLPFJE              9284 //C
#define FID_PGJKJE              9285 //C
#define FID_SGZQFC              9286 //C
#define FID_ZQDFJE              9287 //C
#define FID_ZZLGJE              9288 //C
#define FID_BYSJE               9289 //C
#define FID_SGKFC               9290 //C
#define FID_SGKSR               9291 //C
#define FID_SYSJE               9292 //C
#define FID_WGHZJ               9293 //C
#define FID_WHSGK               9294 //C
#define FID_BRKHSL              9295 //C
#define FID_BRXHSL              9296 //C
#define FID_MCDXSL              9297 //C
#define FID_MRDXSL              9298 //C
#define FID_SGCJSL              9299 //C
#define FID_SHCJSL              9300 //C
#define FID_FEMXLSH             9301 //C
#define FID_FEDZRQ              9302 //C
#define FID_ZJDZRQ              9303 //C
#define FID_FHDJFE              9304 //C
#define FID_FEYE                9305 //C
#define FID_RGJE                9306 //C
#define FID_SHFE                9307 //C
#define FID_BRBD                9308 //C
#define FID_XYJKFSJE            9309 //C
#define FID_XYJKYE              9310 //C
#define FID_FILEZAP             9311 //C
#define FID_MZZL                9312 //C
#define FID_QX                  9313 //C
#define FID_DQBH                9314 //C
#define FID_DFJG                9315 //C
#define FID_FXED                9316 //C
#define FID_FXSL                9317 //C
#define FID_TS                  9318 //C
#define FID_SXFL                9319 //C
#define FID_YQLL                9320 //C
#define FID_TGFL                9321 //C
#define FID_LJJZ                9322 //C
#define FID_MWFSY               9323 //C
#define FID_NSYL                9324 //C
#define FID_TGJE                9325 //C
#define FID_DBGBH               9326 //C
#define FID_DBGRQ               9327 //C
#define FID_DFJE                9328 //C
#define FID_DFLX                9329 //C
#define FID_DFGY                9330 //C
#define FID_DFYYB               9331 //C
#define FID_GSRQ                9332 //C
#define FID_NBDM                9333 //C
#define FID_DBGGY               9334 //C
#define FID_DBGYYB              9335 //C
#define FID_NF                  9336 //C
#define FID_XQJE                9337 //C
#define FID_DBBC                9338 //C
#define FID_XQBC                9339 //C
#define FID_DBGBD               9340 //C
#define FID_XQBD                9341 //C
#define FID_DBGSJ               9342 //C
#define FID_GSSJ                9343 //C
#define FID_DFSJ                9344 //C
#define FID_PLRQ                9345 //C
#define FID_PLSJ                9346 //C
#define FID_DBGJE               9347 //C
#define FID_TGBD                9348 //C
#define FID_SCDBG               9349 //C
#define FID_SCXQ                9350 //C
#define FID_SCTG                9351 //C
#define FID_PZSM                9352 //C
#define FID_QYBZ                9353 //C
#define FID_QYJJDM              9354 //C
#define FID_DXDM                9355 //C
#define FID_DXMC                9356 //C
#define FID_JJFXDJ              9357 //C
#define FID_KHQR                9358 //C
#define FID_GRRGSGDBZGJE        9359 //C
#define FID_GRRGSGDTZGJE        9360 //C
#define FID_MCDJSL              9361 //C
#define FID_JGRGSGDBZGJE        9362 //C
#define FID_JGRGSGDTZGJE        9363 //C
#define FID_LCCPBZ              9364 //C
#define FID_CDYY                9365 //C
#define FID_ZXTBZ               9998 //C
#endif // !defined(_FIDDEF_DEFINE_H)
